### ISSUE TITLE
Dataset questions

### ISSUE THREAD

**Issue by SaSa-123** [rafiibnsultan/GeoSAM#5]
Great work! Hello, I would like to know what formats of data are stored in image_dir, mask_dir and gt_dir in your dataset, and what do these data correspond to?
<img width="396" alt="Snipaste_2024-06-19_17-14-47" src="https://github.com/rafiibnsultan/GeoSAM/assets/79628470/aa558624-4188-485a-82fb-9c9d9315b279">

**Comment by rafiibnsultan** [comment]
These are 2D PNG files.
We have a plan to upload some sample data so people can try it out.

**Comment by rafiibnsultan** [comment]
Hi,

Since you work in a related domain, I was wondering if you would be interested in reviewing this current work as a paper that we plan to submit to a relevant journal. If you are open to this, I can include you as a potential reviewer. For this, I would need your contact information or a link to your Google Scholar profile.

If you're willing to be a potential reviewer, please feel free to reach out to me via email at: hm4013@wayne.edu.
